# prefix: Ctrl+b -> Ctrl+t
unbind C-b
set -g prefix C-t
bind C-t send-prefix

# increase history limit
set -g history-limit 10000000

# start windows and panes at 1 instead of 0 since prefix+0 is hard to type
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# enable mouse support
set -g mouse on

# use - and |(\) to split panes
unbind '"'
unbind %
bind - split-window -v
bind \\ split-window -h

# status bar
set -g status-left "#[fg=black,bg=blue] tmux #[fg=blue,bg=black]"
set -g status-right "#{prefix_highlight}"
set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#W #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-separator ""
set -g @prefix_highlight_output_prefix "#[fg=brightcyan]#[bg=black]#[nobold]#[noitalics]#[nounderscore]#[bg=brightcyan]#[fg=black] "
set -g @prefix_highlight_output_suffix " "
set -g @prefix_highlight_copy_mode_attr "fg=brightcyan,bg=black,bold"

# plugins
set -g @nord_tmux_show_status_content "0"
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin "tmux-plugins/tmux-prefix-highlight"

# automatically install missing plugins and init the plugin manager
# (keep at the very bottom of tmux.conf)
setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.config/tmux/plugins/"
run "/usr/share/tmux-plugin-manager/bin/install_plugins >/dev/null"
run "/usr/share/tmux-plugin-manager/tpm"
